name: Auto Train on PDF Update

on:
  push:
    paths:
      - 'data/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install transformers torch datasets
        
    - name: Convert PDFs to text
      run: |
        mkdir -p text_data
        python scripts/pdf_to_text.py --input ./data --output ./text_data
        
    - name: Prepare training data
      run: |
        python scripts/prepare_training_data.py
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
